version: '3.8'

services:
  dev-db:
    image: postgres:14
    container_name: cicd-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    ports:
      - "5451:5432"

  staging-db:
    image: postgres:14
    container_name: cicd-staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: staging_db
    ports:
      - "5452:5432"

  prod-db:
    image: postgres:14
    container_name: cicd-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prod_db
    ports:
      - "5453:5432"

volumes:
  dev_data:
  staging_data:
  prod_data:
